### ISSUE TITLE
Will not deploy, bad variable names?

### ISSUE THREAD

**Issue by slm4996** [SamEureka/balenaRancher#12]
Upon deploying the page is filled with this error and no variables populate:

Request error: Environment variable names can only contain alphanumeric characters and underscore

**Comment by SamEureka** [comment]
@slm4996 
Did you complete step 2 [here](https://github.com/SamEureka/balenaRancher/blob/main/README.md#balenacloud-setup)?

You need an API key from your balena.io account for the auto-config python script to work.

//Sam

**Comment by slm4996** [comment]
My apologies, I was unaware of this repository until after I attempted to deploy the App from balenaHub: https://hub.balena.io/organizations/sdennon/apps/balenaRancher

The App page there didn't mention that or link to any additional documentation, so I just clicked the "Deploy" button and that is what happened.

I will try deploying this as per the documentation, and not by using the Deploy button on balenaHub. Maybe it would be a good idea to update the app description with a link to the GitHub repo with the directions, and a warning that the deploy button will not work?

![image](https://user-images.githubusercontent.com/37423/192887019-a6db523a-fccc-4ae3-ad9c-60413fdd6801.png)


Thank you for the link to the deployment steps.

**Comment by SamEureka** [comment]
@slm4996 

Thanks so much for the documentation feedback. I just learned that you can add quite a bit of detail into the balena hub description. I will update the description to be more clear about the deploy button. Clearly the scripts won't work unless you already have a fleet with the API_KEY variable declared. There isn't a way to do that automagically that I know of. 

If you don't mind... would you be willing to update this issue with any problems you run into? Even just an update to let me know if it worked for you. I've built clusters from scratch a few times and didn't run into any problems. But I also put the app together so I might be doing something unconsciously that others would need explicit instructions for. 

Again, thanks for the feedback!

//Sam
